### ISSUE TITLE
WailaErrorOutput（Version 1.12.2 viewEMC v6）

### ISSUE THREAD

**Issue by 2781762845** [Silly511/View-EMC#1]
07/23/2018 - 11:11:00
class silly511.viewemc.HwylaPlugin
java.lang.NoSuchMethodError: moze_intel.projecte.utils.EMCHelper.getEmcValue(Lnet/minecraft/item/ItemStack;)I
	at silly511.viewemc.HwylaPlugin.getWailaBody(HwylaPlugin.java:32)
	at mcp.mobius.waila.api.impl.MetaDataProvider.handleBlockTextData(MetaDataProvider.java:120)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:81)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_229_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3938)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:157)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:23)

**Comment by 2781762845** [comment]
This mod shows an error on waila

**Comment by Fadenfire** [comment]
What version of ProjectE do you have?

**Comment by 2781762845** [comment]
ProjectE version PE1.3.1B
The latest version on the curseforge

**Comment by Fadenfire** [comment]
Try using version 1.3.0 of ProjectE.

**Comment by 2781762845** [comment]
I see.I will try it.Thank you.

**Comment by HydrogenC** [comment]
Another projectE addon requires 1.3.1, and I wanna use your mod and that mod together. Please make a seperate version for 1.3.1.

**Comment by Fadenfire** [comment]
I just released a new version of that should work with both 1.3.0 and 1.3.1 of ProjectE.

**Comment by HydrogenC** [comment]
Thanks
