### ISSUE TITLE
invalid mcmod.info

### ISSUE THREAD

**Issue by LlubNek** [Silly511/View-EMC#3]
```
01:13:09 | FML | Client thread | error | The mcmod.info file in ViewEMC-1.12.2-v8.jar cannot be parsed as valid JSON. It will be ignored com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 15 column 2 path $[0].screenshots
 	at com.google.gson.internal.Streams.parse(Streams.java:60)
 	at com.google.gson.JsonParser.parse(JsonParser.java:84)
 	at com.google.gson.JsonParser.parse(JsonParser.java:59)
 	at net.minecraftforge.fml.common.MetadataCollection.from(MetadataCollection.java:63)
 	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:65)
 	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47)
 	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74)
 	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93)
 	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:425)
 	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566)
 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
 	at net.minecraft.client.Minecraft.init(Minecraft.java:467)
 	at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
 	at net.minecraft.client.main.Main.main(SourceFile:123)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:497)
 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 15 column 2 path $[0].screenshots
 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505)
 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
 	at com.google.gson.internal.Streams.parse(Streams.java:48)
 	... 19 more
```
This seems to be caused by the extra comma after the screenshots line in your mcmod.info file.

**Comment by cmoates** [comment]
I added a pull request to fix this error.
